---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2020/4/21 14:25
---
local pbhelper      = require "net.pbhelper"
local websocket 	= require "http.websocket"

local encode 	        = pbhelper.pb_encode

local helper = {}

function helper.write(fd, message)
    local protoName = message.header.proto
    local data      = message.payload
    local errCode   = message.header.errcode
    local msgData 	= encode(protoName, data, errCode)
    websocket.write(fd, msgData, "binary")
end

return helper