---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2018/11/27 11:28
---
local skynet        = require "skynet"
local gateserver    = require "snax.gateserver"

local connection = {}

local handler = {}

local function close_fd(fd)
    local c = connection[fd]
    if c then
        connection[fd] = nil

        skynet.send(c.agent, "lua", "disconnect")
    end
end

function handler.connect(fd, addr)
    local agent = skynet.newservice("agentd")

    local c = {
        fd      = fd,
        agent   = agent,
    }

    connection[fd] = c

    skynet.send(agent, "lua", "connect", fd, addr)
end

function handler.message(fd, msg, sz)
    local c = connection[fd]
    local agent = c.agent
    if agent then
        skynet.send(agent, "lua", "message", msg, sz)
    end
end

function handler.disconnect(fd)
    close_fd(fd)
end

function handler.error(fd, msg)
    close_fd(fd)
end

function handler.warning(fd, size)
end

local CMD = {}

function CMD.accept(fd)
    gateserver.openclient(fd)
end

function CMD.kick(fd)
    gateserver.closeclient(fd)
end

function handler.command(cmd, source, ...)
    local f = assert(CMD[cmd])
    return f(...)
end

gateserver.start(handler)