---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2018/11/6 20:32
---
local json = require("cjson")

local json_codec = {}

function json_codec.encode(cmd, msg)
	local data = json.encode({cmd = cmd, msg = msg})
	return data
end

function json_codec.decode(data)
	local cmd = nil
	local msg = nil

	local decode_data = json.decode(data)
	if decode_data then
		cmd = decode_data.cmd
		msg = decode_data.msg
	end

	return cmd, msg
end

return json_codec