---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2018/11/7 15:28
---
local json_codec	= require("pdk.json_codec")
local poker_type	= require("pdk.poker_type")
local play_state	= require("pdk.play_state")
local ENUM 			= require("config.gameenum")

local PLAY_STATE = ENUM.PLAY_STATE

local play_core = {}

function play_core.new()
	local core = {}
	core.play_mgr 	= {}
	core.play_state = play_state.new()
	setmetatable(core, {__index = play_core})

	local functions = core:auth_state_functions()
	core.play_state:copy_core_functions(functions)

	return core
end

-- 座位通知消息
function play_core:notify(idx, data)
	local notify = self.play_mgr.functions.notify
	if notify then
		notify(idx, data)
	end
end

-- 游戏广播消息
function play_core:broadcast(data)
	local broadcast = self.play_mgr.functions.broadcast
	if broadcast then
		broadcast(data)
	end
end

function play_core:state_notify(idx, state)
	if state == PLAY_STATE.DEAL then
		local data = json_codec.encode("deal")
		self:notify(idx, data)
	elseif state == PLAY_STATE.SNATCH then
		local data = json_codec.encode("snatch")
		self:notify(idx, data)
	end
end

-- 授权给状态模块的函数
function play_core:auth_state_functions()
	local function state_notify(idx, state)
		self:state_notify(idx, state)
	end

	return {state_notify = state_notify}
end

function play_core:copy_play_functions(functions)
	self.play_mgr.functions = functions
end

function play_core:begin(data)
	self.data = data
	self.play_state:begin_and_run()
end

-- 获取某个位置的牌
function play_core:get_cards(idx)
	local place = self.data.places[idx]
	if place then
		return place.cards
	end
end

-- 验证棋牌类型
function play_core:check_type(type, cards)
	return poker_type.check_type(type, cards)
end

-- 获取出牌类型
function play_core:test_type(cards)
	return poker_type.test_type(cards)
end

-- 接收玩家命令
function play_core:update(idx, data)

	local place,state = self.play_state:turn()
	if place == idx then

	end

	self:broadcast(data)
end


return play_core