---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2018/11/5 17:06
---

local poker_play = {}

function poker_play.new(places)
	local play = {places = {}}

	setmetatable(play, {__index = poker_play})

	return play
end

return poker_play