---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2019/5/10 11:52
---
local skynet = require "skynet"

local tb_insert = table.insert

local function get_user_data(pid)
    local ok, result = skynet.call(GLOBAL.SERVICE_NAME.SOCIAL, "lua", "get_user_data", pid)
    if ok == 0 then
        return result
    end
end

local function load_social_data(data_list, result_list)
    for pid in pairs(data_list or {}) do
        local udata = get_user_data(pid)
        if udata then
            tb_insert(result_list, udata)
        end
    end
end

local social = {}

function social.get_user_data(pid)
    return get_user_data(pid)
end

function social.get_friend_data(pid)
    return get_user_data(pid)
end

function social.get_friend_byName(name)

end

function social.get_all_friend_data(data)
    local result =
    {
        friend_list = {},
        black_list  = {},
    }

    load_social_data(data.friend.list, result.friend_list)
    load_social_data(data.enemy.list, result.black_list)

    return result
end

function social.update(pid, data)
    skynet.send(GLOBAL.SERVICE_NAME.SOCIAL, "lua", "update", pid, data)
end

return social