---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dengcs.
--- DateTime: 2019/5/10 11:52
---
local skynet = require "skynet"

local social = {}

function social.get_user_data(pid)
    local ok, result = skynet.call(GLOBAL.SERVICE_NAME.SOCIAL, "lua", "get_user_data", pid)
    if ok == 0 then
        return result
    end
end

function social.get_friend_data(pid)
    local ok, result = skynet.call(GLOBAL.SERVICE_NAME.SOCIAL, "lua", "get_friend_data", pid)
    if ok == 0 then
        return result
    end
end

function social.get_all_friend_data()

end

return social