require "basic.macros"
require "basic.game"
require "basic.errno"

require "basic.ltypes"
require "basic.lstring"
require "basic.ltable"
require "basic.lobject"
require "basic.ltimer"
require "basic.lfunction"
require "basic.ldebugger"
require "basic.errcode"
require "basic.lservice"