---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2019/4/16 10:28
---

local skynet = require "skynet"

-- 序号部分常量定义
local SERVICE_SEQNO_BITS = 10
local SERVICE_SEQNO_MASK = ~(-1 << SERVICE_SEQNO_BITS)

-- 时间部分常量定义
local SERVICE_XTIME_BITS = 30

-- 获取节点编号
local nodeid = tonumber(skynet.getenv("nodeid"))

if nodeid and nodeid > 1024 then
    LOG_ERROR("node[%s] is illegal!!!", nodeid)
end

-- 时间戳
local xtime = 0

-- 序列号
local seqno = 0

local M = {}

-- 分配唯一标识符
function M.generate()
    -- 更新时间戳
    local ctime = math.floor(skynet.time()*100) - 155730000000
    if xtime ~= ctime then
        xtime = ctime
        seqno = 0
    end
    -- 生成序列号
    if seqno >= SERVICE_SEQNO_MASK then
        skynet.sleep(0)
        return M.generate()
    else
        seqno = seqno + 1
        return (seqno | ((nodeid << SERVICE_XTIME_BITS) | xtime) << SERVICE_SEQNO_BITS)
    end
end

-- 分离出节点ID
function M.get_node(pid)
    local pid_no = tonumber(pid)
    return pid_no >> (SERVICE_XTIME_BITS + SERVICE_SEQNO_BITS)
end

return M